apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata:
  name: color-service
spec:
  params: 
  - name: GIT_REPO_URL
    description: The git repository url
  - name: GIT_REVISION
    description: The git revision
    default: develop
  - name: GIT_REF
    description: The git ref
    default: refs/heads/develop
  - name: GIT_REPO_NAME
    description: The name of the deployment to be created / patched
  - name: GIT_REPO_FULL_NAME
    description: Full name of the repository
  resourcetemplates: 
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: color-service-
    spec:
      pipelineRef:
        name: color-service
      params:
      - name: SERVICE_NAME
        value: $(tt.params.GIT_REPO_NAME)
      - name: GIT_REPO_FULL_NAME
        value: $(tt.params.GIT_REPO_FULL_NAME)
      - name: GIT_REPO_URL
        value: $(tt.params.GIT_REPO_URL)
      - name: GIT_REVISION
        value: $(tt.params.GIT_REVISION)
      - name: GIT_REF
        value: $(tt.params.GIT_REF)
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
      - name: source
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            volumeMode: Filesystem
      - name: maven-repo
        persistentVolumeClaim:
          claimName: maven-repo
