apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: color-service
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-repo-revision
    value: $(body.head_commit.id)
  - name: git-repo-ref
    value: $(body.ref)