apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workspace-pipeline
spec:
  description: This pipeline demonstrates the use of workspaces
  params:
  - name: GIT_REPO
    description: The Git Repository which should be cloned into the workspace
    type: string
    default: https://github.com/openshift-pipeline-workshop/color-service.git
  - name: GIT_REVISION
    description: The revision which should be cloned
    type: string
    default: master
  # we need to declare all workspaces used by the pipeline
  workspaces:
  - name: source
  tasks:
    # We are using a predefined cluster task which allows to clone a git repo
    # Run the following command to inspect the cluster task:
    #   tkn clustertask describe git-clone
  - name: git-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
        # "url" is the name of the parameter as specified by the git-clone task
      - name: url
        value: $(params.GIT_REPO)
        # "revision" is the name of the parameter as specified by the git-clone task
      - name: revision
        value: $(params.GIT_REVISION)
    # here we map the workspace output (defined by the task) to the source
    # workspace defined by the pipeline
    workspaces:
      - name: output
        workspace: source
    # Now let's display the content of the source workspace.
    # For that, we are using the tree task
  - name: ls
    taskRef:
      name: ls
    # We need to do some sequencing here. This task obviously only makes sense
    # if it runs after git-clone has finished.
    runAfter:
    - git-clone
    # here we map the workspace content (defined by the task) to the source
    # workspace defined by the pipeline
    workspaces:
    - name: content
      workspace: source
  - name: echo-git-commit
    taskRef:
      name: echo
      kind: ClusterTask
    # The task needs to run after the git clone-task, otherwise the result will be empty
    runAfter:
    - git-clone
    params:
      - name: MESSAGE
        # Here we pass the commit result of the git-clone task into the echo task
        value: $(tasks.git-clone.results.commit)
  - name: echo-git-url
    taskRef:
      name: echo
      kind: ClusterTask
    # The task needs to run after the git clone-task, otherwise the result will be empty
    runAfter:
    - git-clone
    params:
      - name: MESSAGE
        # Here we pass the url result of the git-clone task into the echo task
        value: $(tasks.git-clone.results.url)