apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helm-uninstall
spec:
  params:
  - name: SERVICE_NAME
    description: The helm release prefix
    type: string
  - name: GIT_REF
    description: Git ref
    type: string
  - default: ""
    description: The helm release namespace
    name: RELEASE_NAMESPACE
    type: string
  - default: docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
    description: Specify a specific helm image
    name: HELM_IMAGE
    type: string
  steps:
  - image: $(params.HELM_IMAGE)
    name: uninstall-release
    script: |
      echo "current installed helm releases"
      helm list --namespace "$(params.RELEASE_NAMESPACE)"
      echo "uninstall helm chart..."
      REF_HASH=`echo $(params.GIT_REF) | sha256sum | cut -c1-8`
      helm uninstall --namespace "$(params.RELEASE_NAMESPACE)" "$(params.SERVICE_NAME)-${REF_HASH}"
