apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven
spec:
  workspaces:
  - name: maven-repo
  - name: source
  params:
  - name: GOALS
    description: The Maven goals to run
    type: array
    default: ["package"]
  - name: CONTEXT_DIR
    description: The context directory within the repository for sources on which
      we want to execute maven goals.
    type: string
    default: .
  results:
  - description: The version extracted from the pom.xml file
    name: version
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(params.GOALS)"
    - name: mvn-get-version
      image: gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        mvn -q -Dexec.executable="echo" -Dexec.args='-n ${project.version}' --non-recursive exec:exec > $(results.version.path)

