apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: color-service
spec:
  serviceAccountName: pipeline
  triggers:
  - name: color-service-push
    interceptors:
    - ref:
        name: "github"
        kind: ClusterInterceptor
        apiVersion: triggers.tekton.dev
      params:
      - name: "eventTypes"
        value: ["push"]
    bindings:
    - ref: color-service
    template:
      ref: color-service